<?php

/**
 * BasesfMultiDomain
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $host
 * 
 * @method integer       getId()   Returns the current record's "id" value
 * @method string        getName() Returns the current record's "name" value
 * @method string        getHost() Returns the current record's "host" value
 * @method sfMultiDomain setId()   Sets the current record's "id" value
 * @method sfMultiDomain setName() Sets the current record's "name" value
 * @method sfMultiDomain setHost() Sets the current record's "host" value
 * 
 * @package    ##PROJECT_NAME##
 * @subpackage model
 * @author     ##AUTHOR_NAME##
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfMultiDomain extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_multi_domain');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('host', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}