<?php

/**
 * PluginsfMultiDomainTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfMultiDomainTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfMultiDomainTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfMultiDomain');
    }
}